#!/bin/bash

COMPONENT="Frontend"
ID=$(id -u)
LOG="/tmp/frontend.log"

if [ $ID -ne 0 ]; then
   echo -e "\e[31m Script is expected to be executed as root user or with sudo scriptName.sh \e[0m"
   echo -e "\t sudo bash $0"
   exit 1
fi

stat() {
if [ $1 -eq 0 ] ; then
   echo -e "\e[32m success \e[0m"
else
   echo -e "\e[31m failure \e[0m"
   exit 1
fi 
}

COLOUR() {
echo -e "\e[35m $* \e[0m"

}

if [ -f proxy.conf ] ; the
   $COLOUR proxy file is not present 
if

COLOUR installing nginx
dnf install nginx -y  &>> LOG
stat $?

COLOUR Copying proxy file
cp proxy.conf /etc/nginx/default.d/expense.conf &>> LOG
stat $?


COLOUR Starting Nginx
systemctl enable nginx &>> LOG
stat $?

COLOUR Performing a Cleanup
rm -rf /usr/share/nginx/html/* &>> LOG
stat $?

COLOUR Downloading $COMPONENT
curl -o /tmp/$COMPONENT.zip https://expense-web-app.s3.amazonaws.com/frontend.zip &>> LOG
cd /usr/share/nginx/html 
stat $?

COLOUR Extracting the $COMPONENT
unzip -o /tmp/$COMPONENT.zip &>> LOG
stat $?

COLOUR Starting Nginx
systemctl restart nginx &>> LOG
stat $? 

echo -e "\n\t** $COMPONENT Installation Is Completed **"


